# Generated by Django 2.2.12 on 2021-11-12 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211112_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 5, 25, 56, 9570, tzinfo=utc)),
        ),
    ]
