# Generated by Django 2.2.12 on 2021-11-12 06:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20211112_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 6, 14, 58, 962209, tzinfo=utc)),
        ),
    ]
